config/routes.rb
LegoMarketplace::Application.routes.draw do
  resources :homes

root :to => 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for @home, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                homes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homes/index.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= link_to home.id, home_path(home) %></td>
        <td><%=l home.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_home_path(home), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      home_path(home),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_home_path,
            :class => 'btn btn-primary' %>

app/views/homes/new.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homes/show.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              homes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_home_path(@home), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              home_path(@home),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>LegoMarketplace</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

   </head>
   <body>

    <!-- Jumbotron -->

    <div class="jumbotron masthead">
     <h1>UNLOADR</h1>

    <p>Share and sell your LEGO® designs.</p>
    <p><a class="btn btn-primary btn-large">
      Interested? Email us a picture of your creation
     </a>
    </p>
   </div>

   <!-- Marketing -->

   <div class="container">
    <div class="marketing">
     <center><h1>No instruction manual? No problem!</h1>
      
     </center>
     <div class="row-fluid">
      
      <div class="span4">
       <img class="marketing-img" src="http://www.mocpages.com/user_images/10450/1217780009_SPLASH.jpg">
       <h2>You send us pictures of your LEGO</h2>
       <p>We scan the images and manually build a 3D representation of your design.</p>
      </div>
      
      <div class="span4">
       <img class="marketing-img" src="http://www.brickinstructions.com/04000/4504/074.jpg">
       <h2>We create the manual for FREE</h2>
       <p>We produce PDF manuals providing step by step instructions of how to assemble your design.To ensure you receive credit, we can include your name and photo.</p>
      </div>
      
      <div class="span4">
       <img class="marketing-img" src="http://cdn1.iconfinder.com/data/icons/ie_Financial_set/128/09.png">
       <h2>You sell your instructions on our site</h2>
       <p>We can create and online store for you to sell your manual; in addition, you can sell your manual on sites like eBay.</p>
      </div>
     </div>

     <!-- Footer Line -->
     <hr class="soften">




    </div>

   </div>


  </body>
  </html>